### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by ghost** [Nicolab/crystal-validator#1]
Hello there

I look to this library look good serve input validation, but i got error after try to installing :

```
Unable to satisfy the following requirements:

- `validator *` required by `shard.yml`
Failed to resolve dependencies
```
this happen after i add this to shard.yaml

```
  validator:
    github: nicolab/crystal-validator
```
then , run `shards install`

How i resolve this ? i new on crystal, and i use crystal 0.34.0 . 
Thank you

**Comment by Nicolab** [comment]
Hello,

Can you remove shards.lock please and try: 

```yml
validator:
    github: nicolab/crystal-validator
    version: ~> 1.0.0-rc5
```

---

Just for info, there is an optional helper that should arrive this month to validate class properties via rules (in annotation).

```crystal
@[Rules(
    between: {"Must between 25 et 40", 26, 40},
    not_empty: {"not_empty", "The field is required"},
  )]
```
And the possibility to use validation functions for more complex validations (e.g. checking data and requiring data normalization).

**Comment by ghost** [comment]
@Nicolab it work well. Thank you.

**Comment by Nicolab** [comment]
Great
